name: CI
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 3 * * *"
    - cron: "0 4 * * 1" # weekly: Ceph demo backend

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace --all-targets -- -D warnings
      - run: cargo test --workspace

  property-nightly:
    if: github.event_name == 'schedule' && github.event.schedule == '0 3 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test -p varve-testkit --release
        env:
          PROPTEST_CASES: "200000"

  crash-matrix:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test -p varve-testkit --release --test crash_recovery
        env:
          VARVE_CRASH_ITERS: "100"

  backend-matrix:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend: [garage, seaweedfs, minio]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test -p varve-testkit --test backend_matrix -- --nocapture
        env:
          VARVE_S3_BACKENDS: ${{ matrix.backend }}

  backend-ceph-weekly:
    if: github.event_name == 'schedule' && github.event.schedule == '0 4 * * 1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test -p varve-testkit --test backend_matrix ceph -- --nocapture
        env:
          VARVE_S3_BACKENDS: ceph
